### ISSUE TITLE
Add support for GHC 8.2 (e.g. TcRnExprMode)

### ISSUE THREAD

**Issue by jwaldmann** [mvdan/hint#32]
```
PATH=/opt/ghc/ghc-8.2.0.20170507/bin:$PATH cabal install hint --allow-newer
...
Configuring hint-0.6.0...
Building hint-0.6.0...
Preprocessing library hint-0.6.0...
...
[11 of 19] Compiling Hint.Typecheck   ( src/Hint/Typecheck.hs, dist/build/Hint/Typecheck.o )

src/Hint/Typecheck.hs:46:12: error:
    • Couldn't match type ‘[Char]’ with ‘GHC.TcRnExprMode’
      Expected type: String -> m (Maybe GHC.Type)
        Actual type: GHC.TcRnExprMode -> m (Maybe GHC.Type)
    • In the expression: fmap Just . GHC.exprType
      In an equation for ‘exprType’: exprType = fmap Just . GHC.exprType
   |
46 | exprType = fmap Just . GHC.exprType
   |            ^^^^^^^^^^^^^^^^^^^^^^^^

src/Hint/Typecheck.hs:46:24: error:
    • Couldn't match type ‘m0 GHC.Type’ with ‘GHC.Type’
      Expected type: GHC.TcRnExprMode -> m GHC.Type
        Actual type: GHC.TcRnExprMode -> String -> m0 GHC.Type
    • In the second argument of ‘(.)’, namely ‘GHC.exprType’
      In the expression: fmap Just . GHC.exprType
      In an equation for ‘exprType’: exprType = fmap Just . GHC.exprType
   |
46 | exprType = fmap Just . GHC.exprType
   |                        ^^^^^^^^^^^^
```

**Comment by mvdan** [comment]
This is fairly standard - each new major GHC release tends to break `hint` in some way. That's why the codebase adapts to different GHC versions.

If you look at the commits made around when 8.0 came out, you'll see examples. If you look into it and come up with a patch, I'll be happy to review. I don't think I'll look into it until 8.2 is released.

**Comment by mvdan** [comment]
Please test master with 8.2. I'll wait a few days before doing a release.

**Comment by int-e** [comment]
This is hardly a comprehensive test, but `mueval` seems to work fine with ghc-8.2-rc2.

**Comment by mvdan** [comment]
@int-e thank you - it's been more than two weeks, so I'll just do a release now.
